//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceJavaSOAP
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services/", ConfigurationName="ServiceReferenceJavaSOAP.ServicioWeb")]
    public interface ServicioWeb
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/ServicioWeb/findAllRequest", ReplyAction="http://services/ServicioWeb/findAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        ServiceReferenceJavaSOAP.findAllResponse findAll(ServiceReferenceJavaSOAP.findAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/ServicioWeb/findAllRequest", ReplyAction="http://services/ServicioWeb/findAllResponse")]
        System.Threading.Tasks.Task<ServiceReferenceJavaSOAP.findAllResponse> findAllAsync(ServiceReferenceJavaSOAP.findAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://services/ServicioWeb/edit")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        void edit(ServiceReferenceJavaSOAP.edit1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://services/ServicioWeb/edit")]
        System.Threading.Tasks.Task editAsync(ServiceReferenceJavaSOAP.edit1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/ServicioWeb/findRangeRequest", ReplyAction="http://services/ServicioWeb/findRangeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        ServiceReferenceJavaSOAP.findRangeResponse findRange(ServiceReferenceJavaSOAP.findRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/ServicioWeb/findRangeRequest", ReplyAction="http://services/ServicioWeb/findRangeResponse")]
        System.Threading.Tasks.Task<ServiceReferenceJavaSOAP.findRangeResponse> findRangeAsync(ServiceReferenceJavaSOAP.findRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://services/ServicioWeb/remove")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        void remove(ServiceReferenceJavaSOAP.remove1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://services/ServicioWeb/remove")]
        System.Threading.Tasks.Task removeAsync(ServiceReferenceJavaSOAP.remove1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/ServicioWeb/countRequest", ReplyAction="http://services/ServicioWeb/countResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        ServiceReferenceJavaSOAP.countResponse1 count(ServiceReferenceJavaSOAP.countRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/ServicioWeb/countRequest", ReplyAction="http://services/ServicioWeb/countResponse")]
        System.Threading.Tasks.Task<ServiceReferenceJavaSOAP.countResponse1> countAsync(ServiceReferenceJavaSOAP.countRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/ServicioWeb/findRequest", ReplyAction="http://services/ServicioWeb/findResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        ServiceReferenceJavaSOAP.findResponse1 find(ServiceReferenceJavaSOAP.findRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/ServicioWeb/findRequest", ReplyAction="http://services/ServicioWeb/findResponse")]
        System.Threading.Tasks.Task<ServiceReferenceJavaSOAP.findResponse1> findAsync(ServiceReferenceJavaSOAP.findRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://services/ServicioWeb/create")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        void create(ServiceReferenceJavaSOAP.create1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://services/ServicioWeb/create")]
        System.Threading.Tasks.Task createAsync(ServiceReferenceJavaSOAP.create1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class usuario
    {
        
        private string apellidoField;
        
        private string claveField;
        
        private string correoField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellido
        {
            get
            {
                return this.apellidoField;
            }
            set
            {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class findResponse
    {
        
        private usuario returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public usuario @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class find
    {
        
        private object idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class edit
    {
        
        private usuario entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public usuario entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class create
    {
        
        private usuario entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public usuario entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class countResponse
    {
        
        private int returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class count
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class remove
    {
        
        private usuario entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public usuario entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class findAll
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAll", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class findAllRequest
    {
        
        public findAllRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class findAllResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReferenceJavaSOAP.usuario[] @return;
        
        public findAllResponse()
        {
        }
        
        public findAllResponse(ServiceReferenceJavaSOAP.usuario[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="edit", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class edit1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReferenceJavaSOAP.usuario entity;
        
        public edit1()
        {
        }
        
        public edit1(ServiceReferenceJavaSOAP.usuario entity)
        {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRange", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class findRangeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("range", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] range;
        
        public findRangeRequest()
        {
        }
        
        public findRangeRequest(System.Nullable<int>[] range)
        {
            this.range = range;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class findRangeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReferenceJavaSOAP.usuario[] @return;
        
        public findRangeResponse()
        {
        }
        
        public findRangeResponse(ServiceReferenceJavaSOAP.usuario[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="remove", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class remove1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReferenceJavaSOAP.usuario entity;
        
        public remove1()
        {
        }
        
        public remove1(ServiceReferenceJavaSOAP.usuario entity)
        {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="count", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class countRequest
    {
        
        public countRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class countResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public countResponse1()
        {
        }
        
        public countResponse1(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="find", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class findRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object id;
        
        public findRequest()
        {
        }
        
        public findRequest(object id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class findResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReferenceJavaSOAP.usuario @return;
        
        public findResponse1()
        {
        }
        
        public findResponse1(ServiceReferenceJavaSOAP.usuario @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class create1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReferenceJavaSOAP.usuario entity;
        
        public create1()
        {
        }
        
        public create1(ServiceReferenceJavaSOAP.usuario entity)
        {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ServicioWebChannel : ServiceReferenceJavaSOAP.ServicioWeb, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioWebClient : System.ServiceModel.ClientBase<ServiceReferenceJavaSOAP.ServicioWeb>, ServiceReferenceJavaSOAP.ServicioWeb
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioWebClient() : 
                base(ServicioWebClient.GetDefaultBinding(), ServicioWebClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicioWebPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioWebClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioWebClient.GetBindingForEndpoint(endpointConfiguration), ServicioWebClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioWebClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioWebClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioWebClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioWebClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReferenceJavaSOAP.findAllResponse findAll(ServiceReferenceJavaSOAP.findAllRequest request)
        {
            return base.Channel.findAll(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceJavaSOAP.findAllResponse> findAllAsync(ServiceReferenceJavaSOAP.findAllRequest request)
        {
            return base.Channel.findAllAsync(request);
        }
        
        public void edit(ServiceReferenceJavaSOAP.edit1 request)
        {
            base.Channel.edit(request);
        }
        
        public System.Threading.Tasks.Task editAsync(ServiceReferenceJavaSOAP.edit1 request)
        {
            return base.Channel.editAsync(request);
        }
        
        public ServiceReferenceJavaSOAP.findRangeResponse findRange(ServiceReferenceJavaSOAP.findRangeRequest request)
        {
            return base.Channel.findRange(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceJavaSOAP.findRangeResponse> findRangeAsync(ServiceReferenceJavaSOAP.findRangeRequest request)
        {
            return base.Channel.findRangeAsync(request);
        }
        
        public void remove(ServiceReferenceJavaSOAP.remove1 request)
        {
            base.Channel.remove(request);
        }
        
        public System.Threading.Tasks.Task removeAsync(ServiceReferenceJavaSOAP.remove1 request)
        {
            return base.Channel.removeAsync(request);
        }
        
        public ServiceReferenceJavaSOAP.countResponse1 count(ServiceReferenceJavaSOAP.countRequest request)
        {
            return base.Channel.count(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceJavaSOAP.countResponse1> countAsync(ServiceReferenceJavaSOAP.countRequest request)
        {
            return base.Channel.countAsync(request);
        }
        
        public ServiceReferenceJavaSOAP.findResponse1 find(ServiceReferenceJavaSOAP.findRequest request)
        {
            return base.Channel.find(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceJavaSOAP.findResponse1> findAsync(ServiceReferenceJavaSOAP.findRequest request)
        {
            return base.Channel.findAsync(request);
        }
        
        public void create(ServiceReferenceJavaSOAP.create1 request)
        {
            base.Channel.create(request);
        }
        
        public System.Threading.Tasks.Task createAsync(ServiceReferenceJavaSOAP.create1 request)
        {
            return base.Channel.createAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioWebPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioWebPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/CRUD/ServicioWeb");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioWebClient.GetBindingForEndpoint(EndpointConfiguration.ServicioWebPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioWebClient.GetEndpointAddress(EndpointConfiguration.ServicioWebPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicioWebPort,
        }
    }
}
